spring:
  datasource:
    url: jdbc:mysql://47.104.174.83:3306/test
    username: root
    password: xiguahaha2018
  application:
    name: order-service
mybatis:
  config-location: jdbc:mysql://47.104.174.83:3306/test
server:
  port: 11182