spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://47.104.174.83:3306/test
    username: root
    password: xiguahaha2018
server:
  port: 11183
mybatis:
  config-location: classpath:mapper/*.xml